### ISSUE TITLE
API package?

### ISSUE THREAD

**Issue by 11rchitwood** [jstrin/webadmitr#1]
Hello @jstrin! I've been considering creating an [API package](https://httr.r-lib.org/articles/api-packages.html) for the [WebAdMIT API](https://liaison-intl.github.io/). Do you have access to this API? If so, would you want to collaborate on this package?

Also, do you intend to put this package on CRAN? If not, would you mind if I take the webadmitr name?

**Comment by jstrin** [comment]
@11rchitwood  - Unfortunately, I don't have access to the API at this time.  Development on this package has taken a back seat to some other items. Feel free to use the webadmitr for CRAN. If I resume development, I can rename the package. 

When developing a package for the Webadmit API, I'd suggest collaborating with users from other CASes to make sure that the package works across CASes. 

good luck!

**Comment by 11rchitwood** [comment]
Thanks @jstrin! Consider #1 resolved.
